name: ai_video_generator
description: Short AI video generator app
publish_to: "none"

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_mobile_ads: ^7.0.0
  shared_preferences: ^2.5.3
  http: ^1.6.0
  video_player: ^2.10.0

flutter:
  uses-material-design: true